# Generated by Django 5.2 on 2025-04-27 12:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quarter_from', models.CharField(max_length=2)),
                ('year_from', models.IntegerField()),
                ('quarter_to', models.CharField(max_length=2)),
                ('year_to', models.IntegerField()),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderReportResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_orders', models.IntegerField()),
                ('total_revenue', models.DecimalField(decimal_places=2, max_digits=10)),
                ('average_order_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='stat_analysis.report')),
            ],
        ),
        migrations.CreateModel(
            name='JobReportResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_jobs', models.IntegerField()),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='stat_analysis.report')),
            ],
        ),
        migrations.CreateModel(
            name='UserReportResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_customers_handled', models.IntegerField()),
                ('total_orders_created', models.IntegerField()),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='stat_analysis.report')),
            ],
        ),
    ]
