# Generated by Django 5.2 on 2025-04-29 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stat_analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobreportresult',
            name='average_completion_time_per_type',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='jobreportresult',
            name='jobs_per_status',
            field=models.JSONField(default=dict),
        ),
    ]
