# Generated by Django 5.2 on 2025-04-27 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=10, unique=True)),
                ('job_name', models.CharField(max_length=200)),
                ('state', models.CharField(choices=[('created', 'Created'), ('active', 'Active'), ('completed', 'Completed')], max_length=100)),
                ('job_type', models.CharField(choices=[('regular', 'Regular'), ('wafer_run', 'Wafer Run')], max_length=20)),
                ('starting_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('completion_time', models.FloatField(help_text='Time in days which were spent to complete the job.')),
                ('orders', models.ManyToManyField(blank=True, to='orders.order')),
            ],
        ),
    ]
